import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Example Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Example Next.js!</a>
        </h1>
        <p className={styles.description}>
          Developed and maintained by{' '}
          <code className={styles.code}>KHOI NGUYEN</code>
        </p>
        <div>
          <input className="btn" type="text" placeholder="search" />
          &#xf002;
        </div>
        <div className={styles.grid}>
          <a href="/parallax" className={styles.card}>
            <h2>Parallax &rarr;</h2>
            <p>Parallax animations</p>
          </a>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
